import re
import unittest

from web.app import app


class StrategyLabFrontendTest(unittest.TestCase):
    def test_strategy_lab_no_longer_exposes_option_entries(self):
        with app.test_client() as client:
            html = client.get("/strategy-lab").get_data(as_text=True)

        self.assertNotIn("期" + "权叠加", html)
        self.assertNotIn("option" + "_overlay", html)
        self.assertNotIn("default" + "_option_", html)
        self.assertNotIn("/api/" + "option-quote", html)

    def test_scorecard_detail_button_opens_visible_results_detail(self):
        with app.test_client() as client:
            html = client.get("/strategy-lab").get_data(as_text=True)

        self.assertIn("onclick=\"loadScorecardDetail('${question.key}', '${item.buy_strategy}', '${item.sell_strategy}')\"", html)
        detail_function = re.search(
            r"async function loadScorecardDetail\(questionKey, buyStrategy, sellStrategy\) \{(?P<body>.*?)\n        async function runScorecard",
            html,
            re.S,
        )
        self.assertIsNotNone(detail_function)
        body = detail_function.group("body")
        self.assertIn("activateTab('results')", body)
        self.assertNotIn("activateTab('scorecard')", body)

    def test_scorecard_payload_uses_selected_strategy_filters(self):
        with app.test_client() as client:
            html = client.get("/strategy-lab").get_data(as_text=True)

        self.assertIn("buy_strategies: selectedStrategies('buyStrategy', buyStrategyLabels)", html)
        self.assertIn("sell_strategies: selectedSellStrategies()", html)
        self.assertIn("function applyRobustCandidate(candidateKey)", html)
        self.assertIn("应用参数并看全量评分", html)
        self.assertIn("收益榜口径：收益 90% / 回撤 10%", html)
        self.assertIn("ranking_formula: 'return_90_drawdown_10'", html)
        self.assertNotIn("robust_score_mode", html)
        self.assertNotIn('id="robustScoreMode"', html)
        self.assertNotIn("综合排序", html)
        self.assertNotIn("收益优先 80/20", html)
        self.assertIn('id="scoreSellStrategy"', html)
        self.assertIn("score_sell_strategies: selectedSellStrategies()", html)
        self.assertNotIn('aria-label="解释 P25"', html)
        self.assertNotIn("Top10%", html)
        self.assertNotIn("Bottom10%", html)
        self.assertIn("document.getElementById('robustBoard')", html)
        self.assertIn("setFieldValue('stepPct', candidate.step_pct)", html)
        self.assertIn("setFieldValue('equalSliceAllocation', candidate.equal_slice_allocation_pct)", html)
        self.assertIn('id="coreDipInitialCorePct"', html)
        self.assertIn('id="coreDipWeeklyCorePct"', html)
        self.assertIn('id="coreDipCashReservePct"', html)
        self.assertIn('id="coreDipStartDrawdownPct"', html)
        self.assertIn('id="coreDipFullDrawdownPct"', html)
        self.assertIn('id="coreDipTimingEnabled"', html)
        self.assertIn('id="coreDipTimingMaxDelayDays"', html)
        self.assertIn('id="coreDipTimingRiseThresholdPct"', html)
        self.assertIn('id="coreDipTimingNearLowPct"', html)
        self.assertIn("core_dip_initial_core_pct: readNumber('coreDipInitialCorePct')", html)
        self.assertIn("core_dip_timing_enabled: document.getElementById('coreDipTimingEnabled').value === 'true'", html)
        self.assertIn("default_core_dip_initial_core_pct: readNumber('coreDipInitialCorePct')", html)
        self.assertIn("default_core_dip_timing_enabled: document.getElementById('coreDipTimingEnabled').value === 'true'", html)
        self.assertIn("setFieldValue('coreDipInitialCorePct', candidate.core_dip_initial_core_pct)", html)
        self.assertIn("function coreTimingAllowsBuy", html)
        self.assertIn("买点优化 延迟${number(candidate.core_dip_timing_max_delay_days)}日", html)
        self.assertIn("bits.push('买点优化 关闭')", html)
        self.assertIn("setSelectValue('coreDipTimingEnabled', String(Boolean(candidate.core_dip_timing_enabled)))", html)
        self.assertIn('id="robustCoreDipTimingFilter"', html)
        self.assertIn("core_dip_timing_filter: document.getElementById('robustCoreDipTimingFilter').value", html)
        self.assertIn('id="universeGrid"', html)
        self.assertIn("function initUniverseRows", html)
        self.assertIn("function saveUniverseSymbols", html)
        self.assertIn("default_investment_universe: readInvestmentUniverse()", html)
        self.assertIn("investment_universe: readInvestmentUniverse()", html)
        self.assertIn("const scorecardSymbolKeys =", html)
        self.assertIn("return scorecardSymbolKeys[normalized]", html)
        self.assertNotIn('value="symbol_tsm_us"', html)
        self.assertNotIn('value="symbol_googl_us"', html)
        self.assertNotIn('value="symbol_tsla_us"', html)
        self.assertIn("全局投资标的库", html)
        self.assertIn("function robustCoreDipBuyParams(candidate)", html)
        self.assertIn('id="dcaRearmDrawdown"', html)
        self.assertIn('id="sellStageRearmDrawdown"', html)
        self.assertIn("dca_rearm_drawdown_pct: readNumber('dcaRearmDrawdown')", html)
        self.assertIn("sell_stage_rearm_drawdown_pct: readOptionalNumber('sellStageRearmDrawdown')", html)
        self.assertIn("default_dca_rearm_drawdown_pct: readNumber('dcaRearmDrawdown')", html)
        self.assertIn("default_sell_stage_rearm_drawdown_pct: readOptionalNumber('sellStageRearmDrawdown')", html)
        self.assertIn("setFieldValue('dcaRearmDrawdown', candidate.dca_rearm_drawdown_pct)", html)
        self.assertIn("setFieldValue('sellStageRearmDrawdown', candidate.sell_stage_rearm_drawdown_pct ?? '')", html)
        self.assertIn('id="gridReboundStep"', html)
        self.assertIn('id="gridFirstSellPct"', html)
        self.assertIn('id="gridSecondSellPct"', html)
        self.assertIn('id="gridMinSellAmount"', html)
        self.assertIn("grid_rebound_step_pct: readNumber('gridReboundStep')", html)
        self.assertIn("default_grid_rebound_step_pct: readNumber('gridReboundStep')", html)
        self.assertIn("setFieldValue('gridReboundStep', candidate.grid_rebound_step_pct)", html)
        self.assertIn("function robustGridSellParams(candidate)", html)
        self.assertIn("candidate.grid_rebound_step_pct ?? readNumber('gridReboundStep')", html)
        self.assertIn("网格回弹步长", html)
        self.assertIn("解释网格第一档卖出", html)
        self.assertIn("解释网格第二档卖出", html)
        self.assertIn("解释网格最小卖出额", html)
        self.assertIn('id="costFirstProfitPct"', html)
        self.assertIn('id="costMinSellAmount"', html)
        self.assertIn("cost_first_profit_pct: readNumber('costFirstProfitPct')", html)
        self.assertIn("default_cost_first_profit_pct: readNumber('costFirstProfitPct')", html)
        self.assertIn("setFieldValue('costFirstProfitPct', candidate.cost_first_profit_pct)", html)
        self.assertIn("function robustCostSellParams(candidate)", html)
        self.assertIn("解释成本盈利档位", html)
        self.assertIn("解释成本卖出比例", html)
        self.assertIn("解释成本最小卖出额", html)
        self.assertIn('id="robustEstimate"', html)
        self.assertNotIn('id="robustComputeMode"', html)
        self.assertNotIn("robust_compute_mode: document.getElementById('robustComputeMode').value", html)
        self.assertNotIn("computeMode === 'full'", html)
        self.assertNotIn("candidate_neighborhoods", html)
        self.assertNotIn("fineByKey", html)
        self.assertIn("function scoreCandidateLikeScorecardPage", html)
        self.assertIn("scoreCandidatesLikeScorecardPage", html)
        self.assertIn("候选组合已经包含买入策略、卖出策略和参数的交叉组合", html)
        self.assertIn("评分只比较收益率和最大回撤，固定按收益 90% / 回撤 10% 排名", html)
        self.assertIn("client_full_candidate_return_90_drawdown_10_leaderboard", html)
        self.assertIn("client_parallel_full_candidate_return_90_drawdown_10_leaderboard", html)
        self.assertIn("全候选全题", html)
        self.assertIn("function estimateRobustWorkload()", html)
        self.assertIn('id="robustBuyStrategies" role="group"', html)
        self.assertIn('id="robustSellStrategies" role="group"', html)
        self.assertIn('name="robustBuyStrategy"', html)
        self.assertIn('name="robustSellStrategy"', html)
        self.assertIn("robust-strategy-option", html)
        self.assertIn("querySelectorAll('input[type=\"checkbox\"]:checked')", html)
        self.assertNotIn('id="robustBuyStrategies" multiple', html)
        self.assertNotIn('id="robustSellStrategies" multiple', html)
        self.assertIn("function selectedRobustBuyStrategies()", html)
        self.assertIn("function selectedRobustSellStrategies()", html)
        self.assertIn("buy_strategies: selectedRobustBuyStrategies()", html)
        self.assertIn("sell_strategies: selectedRobustSellStrategies()", html)
        self.assertIn("score_sell_strategies: selectedRobustSellStrategies()", html)
        self.assertIn('id="jobPauseButton"', html)
        self.assertIn('id="jobResumeButton"', html)
        self.assertIn('id="jobCancelButton"', html)
        self.assertIn("async function pauseStrategyJob()", html)
        self.assertIn("async function resumeStrategyJob()", html)
        self.assertIn("async function cancelStrategyJob()", html)
        self.assertIn("${encodeURIComponent(activeStrategyJob.id)}/${action}", html)
        self.assertIn("function clientRobustWorkerSource()", html)
        self.assertIn("new Worker(URL.createObjectURL(new Blob", html)
        self.assertIn("并发自检", html)
        self.assertIn("function runRobustConcurrencyProbe()", html)
        self.assertIn("worker合计", html)
        self.assertIn("/api/strategy-lab/robust/client-packet", html)
        self.assertIn("本机计算 Top10", html)
        self.assertIn("小规模服务端 Top10", html)
        self.assertIn("buyStrategy === 'core_dip_dca'", html)
        self.assertIn("const strategyRegistry =", html)
        self.assertIn("function renderRobustCandidateGridSummary(data)", html)
        self.assertIn("coreTimingVariantMultiplier", html)
        self.assertIn("parameterValues('core_dip_dca', 'core_dip_timing_max_delay_days')", html)
        self.assertIn("grid.core_dip_timing_max_delay_days", html)
        self.assertIn("核心现金垫", html)
        self.assertIn("优化延迟日", html)
        self.assertIn("大涨阈值", html)
        self.assertIn("近低距离", html)
        self.assertIn("return gridVariantCount * rearmMultiplier;", html)
        self.assertIn("预估计算量", html)
        self.assertIn("实际演算", html)
        self.assertIn("解释本次遍历参数", html)
        self.assertIn("解释卖后重启", html)
        self.assertIn("三档金字塔：整仓/网格/成本卖出后", html)
        self.assertIn("解释候选组合", html)
        self.assertNotIn("解释粗筛候选", html)
        self.assertNotIn("解释局部加密候选", html)
        self.assertNotIn("解释最终验证候选", html)
        self.assertIn("function normalizedRangeRatio(value, values)", html)
        self.assertIn("function heatmapFillStyle(ratio, cssVar = '--scan-fill')", html)
        self.assertIn("function scorecardCellHeatStyle(strategy, cells)", html)
        self.assertIn("const scoreRatio = normalizedRangeRatio(strategy.score, scoreValues);", html)
        self.assertIn("style: heatmapFillStyle(scoreRatio, '--score-fill')", html)
        self.assertIn("颜色分位", html)
        self.assertNotIn("returnGap / 18", html)
        self.assertNotIn("drawdownGap / 8", html)
        self.assertIn("setSelectValue('buyStrategy', 'all')", html)
        self.assertIn("setSelectValue('scoreSellStrategy', 'all')", html)
        self.assertIn("保持评分为全量策略", html)
        self.assertIn("卖后重启", html)
        self.assertIn("卖档重启", html)
        self.assertNotIn("第 25 分位数", html)
        self.assertNotIn("强势命中率", html)
        self.assertNotIn("踩坑率", html)
        self.assertIn("defaultSellStrategyKeys = Object.keys(sellStrategyLabels);", html)
        self.assertIn("现在包含网格回弹卖出", html)
        self.assertIn("核心定投+回撤加仓", html)
        self.assertNotIn("平方递增加权细切", html)

    def test_robust_top10_is_independent_and_shares_score_topics(self):
        with app.test_client() as client:
            html = client.get("/strategy-lab").get_data(as_text=True)

        self.assertIn('data-tab="robust"', html)
        self.assertIn('id="robustWorkspace"', html)
        self.assertIn("共享题目矩阵", html)
        self.assertIn("function syncScorecardTopic(changedInput)", html)
        self.assertIn("function syncScorecardPeriod(changedInput)", html)
        self.assertIn("function selectedScorecardPeriods()", html)
        self.assertIn("enabled: !enabledEl || enabledEl.checked", html)
        self.assertIn("当前勾选题目会同时影响收益 Top10 与策略评分", html)

        scan_panel = re.search(
            r'<div id="scanWorkspace".*?<div id="robustWorkspace"',
            html,
            re.S,
        )
        self.assertIsNotNone(scan_panel)
        self.assertNotIn("运行收益 Top10", scan_panel.group(0))

    def test_score_matrix_heatmap_uses_linear_question_range(self):
        with app.test_client() as client:
            html = client.get("/strategy-lab").get_data(as_text=True)

        normalized = re.search(
            r"function normalizedRangeRatio\(value, values\) \{(?P<body>.*?)\n        function heatmapFillStyle",
            html,
            re.S,
        )
        self.assertIsNotNone(normalized)
        self.assertIn("(Number(value || 0) - min) / (max - min)", normalized.group("body"))

        score_style = re.search(
            r"function scorecardCellHeatStyle\(strategy, cells\) \{(?P<body>.*?)\n        function showScoreTooltip",
            html,
            re.S,
        )
        self.assertIsNotNone(score_style)
        body = score_style.group("body")
        self.assertIn("normalizedRangeRatio(strategy.return_pct, returnValues)", body)
        self.assertIn("normalizedRangeRatio(strategy.max_drawdown_pct, drawdownValues)", body)
        self.assertIn("normalizedRangeRatio(strategy.score, scoreValues)", body)
        self.assertIn("heatmapFillStyle(scoreRatio, '--score-fill')", body)

    def test_salary_flow_dca_explanation_is_visible_in_strategy_reference(self):
        with app.test_client() as client:
            html = client.get("/strategy-lab").get_data(as_text=True)

        self.assertIn("查看工资流定投说明", html)
        self.assertIn("月注入资金 × 标的权重 ÷ 4", html)
        self.assertIn("1.4x、2.0x、3.0x、4.0x", html)
        self.assertIn("余额扫入", html)
        self.assertIn("drawdown_boost", html)
        self.assertIn("卖后重启回撤", html)

    def test_parameter_lab_page_exposes_full_matrix_worker_flow(self):
        with app.test_client() as client:
            html = client.get("/strategy-lab/parameter-lab").get_data(as_text=True)

        self.assertIn("Strategy + params full lab", html)
        self.assertIn("/api/strategy-lab/parameter-lab/packet", html)
        self.assertIn("new Worker(parameterLabWorkerUrl)", html)
        self.assertIn("function runWorkerPool(packet, startedAt, diagnostics = null)", html)
        self.assertIn("function scoreParameterResults(packet, partialRows, workerStats, wallMs, candidateIndex = null, diagnostics = null)", html)
        self.assertIn("chunks_completed_per_worker", html)
        self.assertIn("cpu_work_estimate_ms", html)
        self.assertIn("开销明细", html)
        self.assertIn('id="costDetails"', html)
        self.assertIn("function renderParameterDiagnostics(data)", html)
        self.assertIn("function logParameterDiagnostics(data)", html)
        self.assertIn("/api/strategy-lab/parameter-lab/client-diagnostics", html)
        self.assertIn("JS heap 实测不可用", html)
        self.assertIn("performance.memory", html)
        self.assertIn("navigator.deviceMemory", html)
        self.assertIn("simulate_elapsed_ms_sum", html)
        self.assertIn("parallel_efficiency", html)
        self.assertIn("batch_size", html)
        self.assertIn("total_batches", html)
        self.assertIn("if (totalSimulations >= 100000)", html)
        self.assertIn("targetSimulations = 1024", html)
        self.assertIn("maxCandidatesPerBatch = 512", html)
        self.assertIn("function parameterRowCandidate(row, packet = null)", html)
        self.assertIn("Object.defineProperty(row, '_candidate_cache'", html)
        self.assertIn("observations_compacted: true", html)
        self.assertIn("observation_count: observationCount", html)
        self.assertIn("function rankedRowsFor(data, rankMethod = 'normalized')", html)
        self.assertIn("Object.defineProperty(data, '_ranked_rows_cache'", html)
        self.assertIn("partialRows.length = 0", html)
        self.assertIn("function closeProgressFloat(manual = true)", html)
        self.assertIn("function scheduleProgressFloatAutoHide()", html)
        self.assertIn("}, 7000);", html)
        self.assertIn('aria-label="关闭进度"', html)
        self.assertIn('id="matrixHead"', html)
        self.assertIn('id="matrixBody"', html)
        self.assertIn('id="candidateGridSummary"', html)
        self.assertIn("function renderCandidateGridSummary()", html)
        self.assertIn("const selectedParameterValues = {}", html)
        self.assertIn('data-parameter-value-key="${escapeHtml(key)}"', html)
        self.assertIn("function toggleParameterValue(field, valueKey)", html)
        self.assertIn("parameter_lab_selected_values: selectedParameterValuesPayload()", html)
        self.assertIn("value === null || value === undefined ? '关闭' : percentChip(value)", html)
        self.assertIn("固定: ${escapeHtml(options.fixedLabel ?? '--')}", html)
        self.assertNotIn("activeParameterFields", html)
        self.assertNotIn("parameter_lab_active_fields: activeParameterFieldValues()", html)
        self.assertIn("步长候选", html)
        self.assertIn("每步投入", html)
        self.assertIn("核心周投", html)
        self.assertIn("核心现金垫", html)
        self.assertIn("开始加仓", html)
        self.assertIn("满额加仓", html)
        self.assertIn("买点优化", html)
        self.assertIn("优化延迟日", html)
        self.assertIn("大涨阈值", html)
        self.assertIn("近低距离", html)
        self.assertIn("卖后重启", html)
        self.assertIn("LEAPS 信号设置", html)
        self.assertIn('id="leapsSignalToggle"', html)
        self.assertIn("input[type=\"checkbox\"]::before", html)
        self.assertIn("border: solid #ffffff;", html)
        self.assertIn("background: rgb(53, 124, 228);", html)
        self.assertIn('id="leapsLowCashThreshold"', html)
        self.assertIn('id="leapsMinDrawdown"', html)
        self.assertIn('id="leapsPremiumBudgetCap"', html)
        self.assertIn('id="leapsTargetDteLabel"', html)
        self.assertIn("function aggregateLeapsSignals(cells)", html)
        self.assertIn("function renderDetailLeaps(row)", html)
        self.assertIn("正股卖出", html)
        self.assertIn("function formatStockSell(signal)", html)
        self.assertIn("class=\"mini-table leaps-detail-table\"", html)
        self.assertIn("#matrixTable thead th,", html)
        self.assertIn("#detailDrawer table thead th {", html)
        self.assertIn("background: #ffffff;\n            backdrop-filter: none;\n            -webkit-backdrop-filter: none;", html)
        self.assertIn(".leaps-detail-table th:first-child {\n            background: #ffffff;\n        }", html)
        self.assertIn("leaps-reason-chip", html)
        self.assertIn("/api/strategy-lab/parameter-lab/leaps-option-outcomes", html)
        self.assertIn("计算 200-300D 月期权收益", html)
        self.assertIn("function buildLeapsOptionQueue(signals)", html)
        self.assertIn("const queueByKey = new Map();", html)
        self.assertIn("signals: batch.map((queueItem) => queueItem.signal)", html)
        self.assertIn("LEAPS_OPTION_BATCH_SIZE = 5", html)
        self.assertIn("LEAPS_OPTION_OUTCOME_RETRY_DELAYS_MS = [5000, 15000]", html)
        self.assertIn("function requestLeapsOptionOutcomeBatch(payload, queueItems, options = {})", html)
        self.assertIn("停止计算", html)
        self.assertIn("计算本行", html)
        self.assertIn("计算该信号", html)
        self.assertIn("只计算高等级信号", html)
        self.assertIn("function highGradeLeapsOptionSignals(signals)", html)
        self.assertIn("calculateLeapsOptionOutcomesForActiveHighGradeSignals", html)
        self.assertIn("signal.grade === '高'", html)
        self.assertIn("计算 Top3 参数行高等级期权收益", html)
        self.assertIn("计算这些行里的全部高等级 LEAPS 信号", html)
        self.assertIn("TOP_GROUP_LEAPS_OPTION_ROW_LIMIT = 3", html)
        self.assertIn("TOP_GROUP_LEAPS_OPTION_SIGNAL_BUDGET = 300", html)
        self.assertIn("function topGroupLeapsOptionRows(data, rankMethod = currentParameterRankMethod())", html)
        self.assertIn("function buildTopGroupLeapsOptionQueue(rowSignalPairs)", html)
        self.assertIn("runLeapsDetailWorker(row)", html)
        self.assertIn("topic_key: activeDetailTopicKey || '__row__'", html)
        self.assertIn("leapsDetailTasksForActiveScope(sourcePacket)", html)
        self.assertIn("当前题目 LEAPS 明细：", html)
        self.assertIn("参数行全部题目 LEAPS 明细", html)
        self.assertIn("期权卖出日", html)
        self.assertIn("row.leaps_option_summary = entry.summary", html)
        self.assertIn("/api/strategy-lab/parameter-lab/leaps-option-outcomes/batch", html)
        self.assertNotIn("LEAPS_OPTION_QUEUE_CONCURRENCY = 2", html)
        self.assertNotIn("Promise.all(Array.from({ length: Math.min(LEAPS_OPTION_QUEUE_CONCURRENCY", html)
        self.assertIn("当前参数行高等级 LEAPS 信号", html)
        self.assertIn("浏览器批量发起请求；期权定价在服务端完成", html)
        self.assertIn("renderLeapsOptionProgress", html)
        self.assertIn("renderLeapsOptionOutcomeTable", html)
        self.assertIn("function formatLeapsOptionExitStatus(outcome)", html)
        self.assertIn("holding: '持有中'", html)
        self.assertIn("expired_without_stock_sell: '已到期'", html)
        self.assertIn("sold: '正股卖点'", html)
        self.assertIn("currentRun = null;\n                    renderTopGroupLeapsOptionControls();", html)
        self.assertIn('data-leaps-scroll-key="top-signals"', html)
        self.assertIn('data-leaps-scroll-key="option-outcomes"', html)
        self.assertIn('data-leaps-scroll-key="full-groups"', html)
        self.assertIn('data-leaps-scroll-key="group-detail:', html)
        self.assertIn("matrixScrollByKey.set(el.dataset.leapsScrollKey, pos)", html)
        self.assertIn("matrixScrollByKey.get(el.dataset.leapsScrollKey)", html)
        self.assertIn("openDetailsByKey.set(el.dataset.leapsDetailKey, el.open)", html)
        self.assertIn("topic_rank", html)
        self.assertIn("topic_score", html)
        self.assertIn("candidateDetailPayload", html)
        self.assertIn("/api/strategy-lab/parameter-lab/estimate", html)
        self.assertIn("strategyLabPendingParameterCandidate", html)
        self.assertIn("应用到主实验室", html)

    def test_strategy_lab_can_consume_parameter_lab_apply_payload(self):
        with app.test_client() as client:
            html = client.get("/strategy-lab").get_data(as_text=True)

        self.assertIn('/strategy-lab/parameter-lab', html)
        self.assertIn("function applyPendingParameterLabCandidate()", html)
        self.assertIn("localStorage.getItem('strategyLabPendingParameterCandidate')", html)
        self.assertIn("applyRunConfigPayload(payload)", html)
        self.assertIn("sameDay.checked = Boolean(candidate.sell_allow_same_day_sell)", html)
        self.assertIn("已应用 Parameter Lab 参数，并恢复原评分题目与周期", html)
        self.assertIn("loadScorecardDetail(topicKey, cand.buy_strategy, cand.sell_strategy)", html)

    def test_detail_chart_labels_cash_as_post_trade_and_marks_initial_cash(self):
        with app.test_client() as client:
            html = client.get("/strategy-lab").get_data(as_text=True)

        self.assertIn("现金线口径：交易后余额", html)
        self.assertIn("现金线记录每日买卖执行后的余额", html)
        self.assertIn("现金余额（交易后）", html)
        self.assertIn("初始现金（交易前）", html)
        self.assertIn("首日交易后现金", html)
        self.assertIn("首日买入金额", html)
        self.assertIn("现金 USD（交易后）", html)

    def test_parameter_lab_cell_replays_detail_inside_parameter_lab(self):
        with app.test_client() as client:
            html = client.get("/strategy-lab/parameter-lab").get_data(as_text=True)

        self.assertIn("function openCellInLab(rowKey, topicKey)", html)
        self.assertIn("openRowDetail(rowKey, topicKey)", html)
        self.assertIn("function runCellDetailWorker(row, topicKey)", html)
        self.assertIn("include_trades: true", html)
        self.assertIn("include_series: true", html)
        self.assertIn("width: min(1120px, calc(100vw - 36px));", html)
        self.assertIn("height: 360px;", html)
        self.assertIn('id="detailTradeChartExpand"', html)
        self.assertIn("onclick=\"event.stopPropagation(); openCellChartFullscreen();\"", html)
        self.assertIn("onclick=\"openCellChartFullscreen()\"", html)
        self.assertIn('id="cellChartFullscreen"', html)
        self.assertIn('id="fullscreenTradeChart"', html)
        self.assertIn("function clearCellTradeChart(message = '等待重放序列。')", html)
        self.assertIn("if (window.Plotly) Plotly.purge(chart);", html)
        self.assertIn("clearCellTradeChart('等待重放序列。')", html)
        self.assertIn("Plotly.purge(chart);", html)
        self.assertIn("Plotly.Plots.resize(chart)", html)
        self.assertIn("function buildCellTradeChartFigure(cell, options = {})", html)
        self.assertIn("function renderCellTradeChartPlot(chart, cell, options = {})", html)
        self.assertIn("config: { displayModeBar: fullscreen, displaylogo: false, responsive: true }", html)
        self.assertIn("line: { color: '#07689f', width: 2.2 }", html)
        self.assertIn("tradeTrace('buy', '买入', '#ff7e67', 'circle')", html)
        self.assertIn("tradeTrace('sell', '卖出', '#054d76', 'diamond')", html)
        self.assertIn("title: {", html)
        self.assertIn("text: '买卖点 / 现金余额（交易后）'", html)
        self.assertIn("paper_bgcolor: '#fafafa'", html)
        self.assertIn("gridcolor: '#d7ecf8'", html)
        self.assertIn("legend: { orientation: 'h', y: fullscreen ? -0.14 : -0.18, x: 0, yanchor: 'top'", html)
        self.assertIn("function getActiveCellReplayContext()", html)
        self.assertIn("cellDetailCache.get(cellDetailCacheKey(row, topicKey))", html)
        self.assertIn(".chart-fullscreen-summary .stat strong", html)
        self.assertIn("text-overflow: ellipsis;", html)
        self.assertIn("function compactCellChartCombinationLabel(row)", html)
        self.assertIn("cellChartFullscreenMetric('参数组合', compactCellChartCombinationLabel(row), { title: fullCombinationLabel, wide: true })", html)
        self.assertIn("title.textContent = compactCellChartCombinationLabel(context.row)", html)
        self.assertIn("title.title = parameterRowCandidate(context.row)?.label || context.row.key || ''", html)
        self.assertIn("function openCellChartFullscreen()", html)
        self.assertIn("function closeCellChartFullscreen()", html)
        self.assertIn("function handleCellChartFullscreenBackdrop(event)", html)
        self.assertIn("function handleCellChartFullscreenKeydown(event)", html)
        self.assertIn("event.key === 'Escape'", html)
        self.assertIn("document.addEventListener('keydown', handleCellChartFullscreenKeydown)", html)
        self.assertIn("closeCellChartFullscreen();\n            document.getElementById('detailDrawer').classList.remove('show');", html)
        self.assertIn("renderCellChartFullscreenSummary(context)", html)
        self.assertIn("买入/卖出", html)
        self.assertIn("日期范围", html)
        self.assertIn("重放一致性", html)
        self.assertIn("id=\"detailTradesSection\"", html)
        self.assertIn("function renderDetailLeapsIntoDrawer(row, preserveScroll = false)", html)
        self.assertIn("function renderParameterMatrixPreservingScroll()", html)
        self.assertIn("不一致: 原 cell 与详情重放指标不同。", html)
        self.assertNotIn("source: 'parameter-lab-cell'", html)
        self.assertNotIn("window.open('/strategy-lab?apply_parameter_lab=1&auto_run_lab=1'", html)


if __name__ == "__main__":
    unittest.main()
